name: Build & Run Docker

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21 (for building the project)
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'

      - name: Build the Java project (Maven)
        run: mvn clean package -DskipTests

      - name: List files in target directory (debugging)
        run: ls -al target

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build app image
        run: docker build -t testdevs/cartapi:latest .

      - name: Push Docker image to Docker Hub
        run: docker push testdevs/cartapi:latest

      - name: Spin up MySQL + App
        run: docker-compose up -d
